In [2]:
import pandas as pd
import os
from bs4 import BeautifulSoup
import requests
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import random

In [2]:
html="""<div class="factionsList_3qfs"><a class="factionWrapper_9Uuf" href="/en_GB/region/bandle-city/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/109f1c35b08e87598eaa1e0755a992e17d9425c2-1920x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/bandle_city_crest_icon.png" alt="Bandle City"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Bandle City</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/bilgewater/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/9700d7bf76ec15c8c526f7fea2a960e3846e44a6-2825x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/bilgewater_crest_icon.png" alt="Bilgewater"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Bilgewater</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/demacia/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/5b80fe8ddd3d935c3f258f3e145b8aed4b7460bf-1920x887.jpg&quot;);"></div><img class="crest_MN39" src="/images/demacia_crest_icon.png" alt="Demacia"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Demacia</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/ionia/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/1691574092da433ea3a4c896c96f8c87d5f7e45a-1920x888.jpg&quot;);"></div><img class="crest_MN39" src="/images/iona_crest_icon.png" alt="Ionia"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Ionia</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/ixtal/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/1a75d072fa01ec3d0cda3f87fc1bf18dce736424-5000x2811.jpg&quot;);"></div><img class="crest_MN39" src="/images/ixtal_crest_icon.png" alt="Ixtal"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Ixtal</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/noxus/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/6310fe5db818f80b84ee784a746cc28ee1273e6b-1920x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/noxus_crest_icon.png" alt="Noxus"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Noxus</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/piltover/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/6c77423961def6e3a82d9a36545782f1a06386e0-4681x2114.jpg&quot;);"></div><img class="crest_MN39" src="/images/piltover_crest_icon.png" alt="Piltover"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Piltover</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/shadow-isles/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/94e4bf2e1b30ba553b4fc0f93e94983837082210-2503x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/shadow_isles_crest_icon.png" alt="Shadow Isles"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Shadow Isles</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/shurima/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/3f24f923ba9871dd870c0d3565075ff8140f44b8-1920x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/shurima_crest_icon.png" alt="Shurima"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Shurima</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/mount-targon/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/8ad3cfba4b5d7cb812562108a6e90d07e0865b3f-1920x1041.jpg&quot;);"></div><img class="crest_MN39" src="/images/mt_targon_crest_icon.png" alt="Targon"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Targon</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/freljord/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/ee60551d26850cfbff088f571bc5e1688b1a143b-2034x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/freljord_crest_icon.png" alt="The Freljord"><h3 class="QH3_hextech_root_f154 factionName_2meu"> The Freljord</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/void/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/7107e5dbca7887931748e7ae0924e6eda17ef6f4-1920x1064.jpg&quot;);"></div><img class="crest_MN39" src="/images/void_crest_icon.png" alt="The Void"><h3 class="QH3_hextech_root_f154 factionName_2meu"> The Void</h3></div></div></a><a class="factionWrapper_9Uuf" href="/en_GB/region/zaun/"><div class="QCard_hextech_wrapper_7db5"><div class="QCard_hextech_root_a9df QCard_hextech_clickable_275e factionCard_3IJ6" tabindex="0"><div class="QBackground_hextech_root_5bd4 background_3pH4" style="background-position: right top; background-image: url(&quot;https://cmsassets.rgpub.io/sanity/images/dsfx7636/universe/56d6fa8581379d60cc17951edbe3d686e52bf51b-1730x1080.jpg&quot;);"></div><img class="crest_MN39" src="/images/zaun_crest_icon.png" alt="Zaun"><h3 class="QH3_hextech_root_f154 factionName_2meu"> Zaun</h3></div></div></a></div>"""

In [27]:
def scrape_elements_v2(url, class_name):
    # Set up the Selenium WebDriver
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")  # Run in headless mode
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    
    try:
        # Open the webpage
        driver.get(url)
        time.sleep(5)  # Wait for JavaScript to load content

        # Get the page source after rendering
        soup = BeautifulSoup(driver.page_source, 'html.parser')

        # Find all elements with the given class
        elements = soup.find_all(class_=class_name)

        return [element.get_text(strip=True) for element in elements]
    
    finally:
        driver.quit()  # Close the browser

In [19]:
url = "https://universe.leagueoflegends.com/en_GB/region/" 
class_name = "factionName_2meu"

# Parse the page content with BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Find all elements with the given class
elements = soup.find_all(class_=class_name)
elements = [element.get_text(strip=True) for element in elements]
faction_list = []
for i, element in enumerate(elements, 1):
	faction_list.append(element)

In [87]:
dict_champion_region = {
      'Champion': [],
      'Region': []
}

for faction in faction_list:
    faction_url = faction.lower().replace('the ', '').replace(' ', '-').replace('targon', 'mount-targon')
    champions = scrape_elements_v2(url+faction_url+"/", "copy_xxN7")
    for champion in champions:
            
            dict_champion_region['Champion'].append(champion)
            dict_champion_region['Region'].append(faction)
    
    
df_region = pd.DataFrame(data=dict_champion_region)
df_region['Champion'] = df_region.apply(lambda x : x['Champion'].replace(x['Region'], '').replace('Freljord', ''), axis=1)

In [50]:
def scrape_table(url, class_name):
    # Send a GET request to the URL
    response = requests.get(url)
    
    # Check if the request was successful
    if response.status_code != 200:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        return None
    
    # Parse the page content with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the table with the given class
    table = soup.find('table', class_=class_name)
    
    if not table:
        print("Table not found")
        return None
    
    # Extract table rows
    rows = table.find_all('tr')
    data = []
    
    for row in rows:
        cols = row.find_all(['th', 'td'])
        data.append([col.get_text(strip=True) for col in cols])
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    return df

In [95]:
df_champion_statistics = scrape_table("https://leagueoflegends.fandom.com/wiki/List_of_champions/Base_statistics", "wikitable")
df_champion_statistics.columns = df_champion_statistics.iloc[0]
df_champion_statistics = df_champion_statistics[1:]
df_champion_statistics

,Champions,HP,HP+,HP5,HP5+,MP,MP+,MP5,MP5+,AD,AD+,AS,AS+,AR,AR+,MR,MR+,MS,Range
1,Aatrox,650,+114,3,+0.5,0,+0,0,+0,60,+5,0.651,+2.5%,38,+4.8,32,+2.05,345,175
2,Ahri,590,+104,2.5,+0.6,418,+25,8,+0.8,53,+3,0.668,+2.2%,21,+4.7,30,+1.3,330,550
3,Akali,600,+119,9,+0.9,200,+0,50,+0,62,+3.3,0.625,+3.2%,23,+4.7,37,+2.05,345,125
4,Akshan,630,+107,3.75,+0.65,350,+40,8.2,+0.7,52,+3,0.638,+4%,26,+4.7,30,+1.3,330,500
5,Alistar,685,+120,8.5,+0.85,350,+40,8.5,+0.8,62,+3.75,0.625,+2.125%,47,+4.7,32,+2.05,330,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Zeri,600,+110,3.25,+0.7,250,+45,6,+0.8,56,+2,0.658,+2%,24,+4.2,30,+1.3,330,500
167,Ziggs,606,+106,6.5,+0.6,480,+23.5,8,+0.8,55,+3.1,0.656,+2%,21,+4.7,30,+1.3,325,550
168,Zilean,574,+96,5.5,+0.5,452,+50,11.35,+0.8,52,+3,0.658,+2.13%,24,+5,30,+1.3,335,550
169,Zoe,630,+106,7.5,+0.6,425,+25,8,+0.65,58,+3.3,0.658,+2.5%,21,+4.7,30,+1.3,340,550
170,Zyra,574,+93,5.5,+0.5,418,+25,7,+0.8,53,+3.2,0.681,+2.11%,29,+4.2,30,+1.3,340,575

In [96]:
df_champion_statistics = df_champion_statistics[['Champions', 'HP', 'AD', 'AS', 'AR', 'MR', 'MS', 'MP']].rename(columns={
    'Champions': 'Champion',
	'HP': 'healthPoints', 
    'AD':'attackDamage', 
    'AS': 'attackSpeed',
    'AR': 'armor', 
    'MR': 'magicResist',
    'MS': 'movementSpeed',
    'MP': 'ressourceType'
    })
df_champion_statistics.loc[df_champion_statistics['ressourceType'] != "0", 'ressourceType'] = "mana" 
df_champion_statistics.loc[df_champion_statistics['ressourceType'] == "0", 'ressourceType'] = "energy"

In [91]:
champion_regions = {
    "Aatrox": "Unknown",
    "Alistar": "Runeterra",
    "Annie": "Noxus",
    "Bard": "Unknown",
    "Bel'Veth": "The Void",
    "Brand": "Runeterra",
    "Evelynn": "Unknown",
    "Fiddlesticks": "Unknown",
    "Hwei": "Ionia",
    "Jax": "Icathia",
    "K'Sante": "Shurima",
    "Kindred": "Unknown",
    "Kled & Skaarl": "Noxus",
    "Mega Gnar": "Freljord",
    "Nami": "Bilgewater",
    "Nilah": "Kathkan",
    "Nocturne": "Unknown",
    "Ryze": "Runeterra",
    "Senna": "Shadow Isles",
    "Shaco": "Unknown",
    "Smolder": "Camavor",
    "Zilean": "Icathia"
}

In [97]:
df_champions = pd.merge(df_region, df_champion_statistics, how='right', on='Champion')
df_champions.loc[df_champions['Region'].isna(), 'Region'] = df_champions.loc[df_champions['Region'].isna(), 'Champion'].apply(lambda x : champion_regions[x])

In [183]:
df_champions = pd.read_csv("./data/processed/df_champion.csv")
df_champions

,Unnamed: 0,Champion,Region,healthPoints,attackDamage,attackSpeed,armor,magicResist,movementSpeed,ressourceType,role
0,0,Aatrox,Unknown,650,60,0.651,38.0,32.0,345,energy,Support
1,1,Ahri,Ionia,590,53,0.668,21.0,30.0,330,mana,Jungle
2,2,Akali,Ionia,600,62,0.625,23.0,37.0,345,mana,ADC
3,3,Akshan,Shurima,630,52,0.638,26.0,30.0,330,mana,ADC
4,4,Alistar,Runeterra,685,62,0.625,47.0,32.0,330,mana,Support
...,...,...,...,...,...,...,...,...,...,...,...
165,165,Zeri,Zaun,600,56,0.658,24.0,30.0,330,mana,Jungle
166,166,Ziggs,Zaun,606,55,0.656,21.0,30.0,325,mana,ADC
167,167,Zilean,Icathia,574,52,0.658,24.0,30.0,335,mana,ADC
168,168,Zoe,Targon,630,58,0.658,21.0,30.0,340,mana,Support
169,169,Zyra,Ixtal,574,53,0.681,29.0,30.0,340,mana,Top

In [100]:
df_players = pd.DataFrame()
for file in os.listdir("./data/"):
    df_temp = pd.read_csv(f"./data/{file}")
    df_temp['Region'] = file[:3]
    df_temp['Year'] = "20"+file.split("20")[1][:2]
    df_players = pd.concat([df_players, df_temp[['Player', 'Team', 'Pos', 'Region', 'Year']]])

In [127]:
roles = list(df_players['Pos'].unique())
def attribute_role(row):
    role = roles[round(random.random()*5)-1]
    return role

In [167]:
df_champions['role'] = df_champions.apply(attribute_role, axis=1)
df_champions

,Champion,Region,healthPoints,attackDamage,attackSpeed,armor,magicResist,movementSpeed,ressourceType,role
0,Aatrox,Unknown,650,60,0.651,38,32,345,energy,ADC
1,Ahri,Ionia,590,53,0.668,21,30,330,mana,Jungle
2,Akali,Ionia,600,62,0.625,23,37,345,mana,Jungle
3,Akshan,Shurima,630,52,0.638,26,30,330,mana,Top
4,Alistar,Runeterra,685,62,0.625,47,32,330,mana,Top
...,...,...,...,...,...,...,...,...,...,...
165,Zeri,Zaun,600,56,0.658,24,30,330,mana,ADC
166,Ziggs,Zaun,606,55,0.656,21,30,325,mana,Top
167,Zilean,Icathia,574,52,0.658,24,30,335,mana,Support
168,Zoe,Targon,630,58,0.658,21,30,340,mana,Top
169,Zyra,Ixtal,574,53,0.681,29,30,340,mana,Top

In [194]:
def select_champion_randomly(row):
	df_temp_champion = df_champions.loc[df_champions['role'] == row['Pos']].copy()
	df_temp_champion = df_temp_champion.reset_index(drop=True)
    
	champ_index = round(random.random()*len(df_temp_champion))
	selected_champ = df_champions.loc[champ_index, 'Champion']
	return selected_champ

In [186]:
df_temp = df_players[['Player', 'Pos']].copy()
df_temp

     Player      Pos
0    1Jiang      Top
1       1xn      ADC
2       369      Top
3       Aki   Jungle
4       Ale      Top
..      ...      ...
388    YSKM      Top
389  Yuekai   Middle
390     Zdz      Top
391    Zhuo  Support
392    Zika      Top

[393 rows x 2 columns]

In [195]:
df_temp = df_temp.groupby(['Player', 'Pos']).count().reset_index()
df_temp['Champion'] = df_temp.apply(select_champion_randomly, axis=1)
df_temp

     Player      Pos      Champion
0       113   Jungle  Fiddlesticks
1    1Jiang      Top         Amumu
2       1xn      ADC          Azir
3       369      Top        Akshan
4      Able      ADC    Cassiopeia
..      ...      ...           ...
250  shanji      Top         Amumu
251   sheer      Top         Annie
252  sorrow   Jungle        Darius
253   vital  Support         Amumu
254     xqw   Middle         Braum

[255 rows x 3 columns]

In [198]:
df_final_players = pd.merge(df_players, df_temp, how='left', on=['Player', 'Pos'])
df_final_players.to_csv("./data/processed/df_players.csv", index=False)

In [170]:
len(df_players.loc[df_players['Region'] == "LPL", "Team"].unique())

17

In [175]:
df_players.loc[(df_players['Year'] == 2024) & (df_players['Team'] == "BNK FEARX")]

      Player       Team      Pos Region  Year
145    Clear  BNK FEARX      Top    LCK  2024
146   Clozer  BNK FEARX   Middle    LCK  2024
154     Duro  BNK FEARX  Support    LCK  2024
156  Execute  BNK FEARX  Support    LCK  2024
162     Hena  BNK FEARX      ADC    LCK  2024
186   Raptor  BNK FEARX   Jungle    LCK  2024

In [179]:
df_players = pd.read_csv("./data/processed/df_players.csv")
test = df_players.groupby(['Team', 'Year'])['Player'].count().reset_index()
test.loc[test['Player'] != 5]

                   Team  Year  Player
2             BNK FEARX  2024       6
4       Bilibili Gaming  2024       6
6             DN Freecs  2024       6
7             DN Freecs  2025       6
8                   DRX  2024       8
9                   DRX  2025       6
10            Dplus KIA  2024       6
16      FunPlus Phoenix  2024       6
30           KT Rolster  2024       6
34           LGD Gaming  2024       6
40    Ninjas in Pyjamas  2024       6
42    Nongshim RedForce  2024       9
44  OKSavingsBank BRION  2024       9
45  OKSavingsBank BRION  2025       6
51  Royal Never Give Up  2024      10
55                   T1  2024       4

In [180]:
df_players

     Player                Team      Pos Region  Year
0    1Jiang         Ultra Prime      Top    LPL  2025
1       1xn  ThunderTalk Gaming      ADC    LPL  2025
2       369         Top Esports      Top    LPL  2025
3       Aki   Ninjas in Pyjamas   Jungle    LPL  2025
4       Ale           JD Gaming      Top    LPL  2025
..      ...                 ...      ...    ...   ...
388    YSKM     Invictus Gaming      Top    LPL  2024
389  Yuekai         Ultra Prime   Middle    LPL  2024
390     Zdz     FunPlus Phoenix      Top    LPL  2024
391    Zhuo   Ninjas in Pyjamas  Support    LPL  2024
392    Zika         LNG Esports      Top    LPL  2024

[393 rows x 5 columns]

In [ ]:
def scrape_table(url, class_name):
    # Send a GET request to the URL
    response = requests.get(url)
    
    # Check if the request was successful
    if response.status_code != 200:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        return None
    
    # Parse the page content with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the table with the given class
    elements = soup.find_all(class_=class_name)
    return [element.get_text(strip=True) for element in elements]
dict_player_nationality = {
	'Player': [],
	'Nationality': []
}
for player in list(df_players['Player'].unique()):
	test = scrape_table(f"https://lol.fandom.com/wiki/{player}", "markup-object country-object")
	if test:
		if len(test) == 0:
			dict_player_nationality['Nationality'].append('unknown')
		else:
			dict_player_nationality['Nationality'].append("/".join(test))
	else:
		dict_player_nationality['Nationality'].append('unknown')

	dict_player_nationality['Player'].append(player)
df_players = pd.merge(df_players, pd.DataFrame(data=dict_player_nationality), how='left', on=['Player'])

In [ ]:
mapping_roles = {'Support': 'Support',
 'Jungle': 'Jungle',
 'Middle': 'Midlane',
 'ADC': 'Botlane',
 'Top': 'Toplane'}

df_champions['role'] = df_champions['role'].apply(lambda x : mapping_roles[x])

In [ ]:
def select_champion_randomly(row):
	# print(f"{df_champions['role']} == {row['Pos']}")
	df_temp_champion = df_champions.loc[df_champions['role'] == row['Pos']].copy()
	df_temp_champion = df_temp_champion.reset_index(drop=True)
	champ_index = round(random.random()*(len(df_temp_champion)-1))
	selected_champ = df_temp_champion.loc[champ_index, 'Champion']
	return selected_champ

In [ ]:
df_players['Champion'] = df_players.apply(select_champion_randomly, axis=1)
df_players.loc[df_players['Pos'] == 'Midlane']

Filling empty player nationality

In [13]:
df_players = pd.read_csv("./data/processed/df_players.csv")
df_players.loc[df_players['Nationality'] == 'unknown' ,['Player', 'Region', 'Nationality']].to_dict('records')

[{'Player': 'Aki', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Angel', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'bat', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Bin', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Cube', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Hope', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Kael', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'knight', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Lele', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Light', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Saber', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'sorrow', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Tarzan', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Wei', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Faker', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Berserker', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'BuLLDoG', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Clear', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Doran', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'DuDu', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Fisher', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Hype', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Lucid', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'PerfecT', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Raptor', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Rich', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Smash', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Viper', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Way', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Zeka', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Faker', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'BuLLDoG', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Calix', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Clear', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Doran', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'DuDu', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'FATE', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Fisher', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Frog', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Lucid', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'PerfecT', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Quantum', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Raptor', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Viper', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Zeka', 'Region': 'LCK', 'Nationality': 'unknown'},
 {'Player': 'Adam', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Alvaro', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Closer', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Ice', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Jun', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Noah', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Adam', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Alvaro', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Closer', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Ice', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Jun', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Noah', 'Region': 'LEC', 'Nationality': 'unknown'},
 {'Player': 'Aki', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Angel', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Bin', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Hope', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Kael', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'knight', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Light', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Mark', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Tarzan', 'Region': 'LPL', 'Nationality': 'unknown'},
 {'Player': 'Wei', 'Region': 'LPL', 'Nationality': 'unknown'}]

In [15]:
mappign_player_nationality = {
    'Aki': 'South Korean',
    'Angel': 'Chinese',
    'bat': 'Chinese',
    'Bin': 'Chinese',
    'Cube': 'Chinese',
    'Hope': 'Chinese',
    'Kael': 'Chinese',
    'knight': 'Chinese',
    'Lele': 'Chinese',
    'Light': 'Chinese',
    'Saber': 'Chinese',
    'sorrow': 'Chinese',
    'Tarzan': 'South Korean',
    'Wei': 'Chinese',
    'Faker': 'South Korean',
    'Berserker': 'South Korean',
    'BuLLDoG': 'South Korean',
    'Clear': 'South Korean',
    'Doran': 'South Korean',
    'DuDu': 'South Korean',
    'Fisher': 'South Korean',
    'Hype': 'South Korean',
    'Lucid': 'South Korean',
    'PerfecT': 'South Korean',
    'Raptor': 'South Korean',
    'Rich': 'South Korean',
    'Smash': 'South Korean',
    'Viper': 'South Korean',
    'Way': 'South Korean',
    'Zeka': 'South Korean',
    'Calix': 'South Korean',
    'FATE': 'South Korean',
    'Frog': 'South Korean',
    'Quantum': 'South Korean',
    'Adam': 'French',
    'Alvaro': 'Spanish',
    'Closer': 'Turkish',
    'Ice': 'South Korean',
    'Jun': 'South Korean',
    'Noah': 'South Korean',
    'Mark': 'Chinese'
}

In [16]:
df_players.loc[df_players['Nationality'] == 'unknown' ,['Nationality']] = \
    df_players.loc[df_players['Nationality'] == 'unknown' ,['Player', 'Nationality']].apply(lambda x : mappign_player_nationality[x['Player']], axis=1)
df_players.loc[df_players['Nationality'] == 'unknown' ,['Nationality']]

Empty DataFrame
Columns: [Nationality]
Index: []

In [19]:
df_players.to_csv('./data/processed/df_players.csv', index=False)